import Header from '@/components/Header';
import Head from 'next/head';
import Feed from '@/components/Feed';
import Modal from '@/components/Modal';
import Modalstory from '@/components/Modalstory';
import Modalchat from '@/components/Modalchat';
import Modaldispstory from '@/components/Modaldispstory';
import Modalvideo from '@/components/Modalvideo';

export default function Home() {
  return (
    <>
      <Head>
        <title>INSTACLONE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/insta.png" />
      </Head>
      <div className='relative'>
        <div className='animatedBackground'></div>
        <div className='scrollbar-thin scrollbar-thumb-[black] relative'>
          {/* Header */}
          <Header />
          {/* Feed */}
          <Feed />
          {/* Modals */}
          <Modal />
          <Modalstory />
          <Modalchat />
          <Modaldispstory />
          <Modalvideo />
        </div>
      </div>
      <style jsx>{`
        @keyframes moveBackground {
          0% { background-position: 0 0; }
          100% { background-position: 100% 100%; }
        }

        .animatedBackground {
          position: absolute;
          width: 100%;
          height: 100%;
          background: linear-gradient(white, white, transparent);
          background-size: 400% 400%;
          animation: moveBackground 15s infinite linear;
          z-index: -1; /* Make sure it stays behind the content */
        }
      `}</style>
    </>
  )
}
